// Libellés français communs des événements de surveillance. Source unique :
// les écrans gardent leurs propres libellés, mais tout identifiant technique
// absent de leur table passe par ici — jamais d'identifiant anglais à l'écran.
const SHARED: Record<string, string> = {
  mouse_left_window: 'Souris sortie de la fenêtre',
  whisper_detected: 'Chuchotement détecté',
  sustained_audio_detected: 'Bruit prolongé détecté',
  talking_detected: 'Parole détectée',
  audio_suspicious: 'Bruit suspect détecté',
  face_reference_captured: 'Photo de référence capturée',
  face_reference: 'Photo de référence',
  face_detection_unavailable: 'Détection du visage indisponible',
  live_monitoring_unavailable: 'Surveillance en direct indisponible',
  low_bandwidth_mode: 'Mode faible débit activé',
  pause_started: 'Pause démarrée',
  pause_ended: 'Pause terminée',
  face_hidden_object_detected: 'Objet devant le visage détecté',
  face_detected: 'Visage détecté',
  face_present: 'Visage présent',
  face_absent: 'Visage absent',
  face_covered: 'Visage partiellement masqué',
  no_face_detected: 'Visage non détecté',
  no_face_low_light: 'Visage non détecté (éclairage faible)',
  suspect_object_detected: 'Objet suspect détecté',
  suspect_object_confirmed: 'Objet suspect confirmé par deux modèles',
  liveness_check_failed: 'Contrôle de vivacité échoué (aucun clignement détecté)',
  multi_screen_detected: 'Plusieurs écrans détectés',
  gaze_away: "Regard détourné de l'écran",
  head_turned: 'Tête tournée',
  mismatch_detected: "Identité différente de la photo de référence",
  identity_mismatch: "Identité différente de la photo de référence",
  identity_mismatch_sustained: "Identité différente de la photo de référence (durable)",
  identity_manual_review: "Vérification manuelle d'identité demandée",
  identity_cleared: 'Identité confirmée',
  teacher_identity_cleared: "Identité confirmée par l'enseignant",
  env_scan_completed: 'Scan environnement effectué',
  env_scan_person_detected: 'Personne détectée dans la pièce',
  env_scan_unavailable: 'Scan environnement indisponible',
  pattern_multi_face_audio: 'Plusieurs visages et bruit simultanés',
  pattern_head_turned_talking: 'Tête tournée et parole simultanées',
  pattern_gaze_talk_mouth: 'Regard détourné et bouche en mouvement',
  pattern_mouth_covered_audio: 'Bouche couverte et bruit simultanés',
  pattern_object_gaze_away: 'Objet suspect et regard détourné',
  pattern_whisper_gaze: 'Chuchotement et regard détourné',
  telemetry_anomaly: 'Volume anormal de signaux',
  teacher_warning: "Avertissement de l'enseignant",
  teacher_message: "Message de l'enseignant",
  teacher_email: "E-mail de l'enseignant",
  teacher_ban: "Exclusion par l'enseignant",
  teacher_private_call: 'Appel privé enseignant',
  teacher_end_call: "Fin d'appel enseignant",
  tab_closed: 'Onglet/navigateur fermé pendant la composition',
  tab_switch: "Changement d'onglet",
  window_blur: 'Changement de fenêtre',
  fullscreen_exit: 'Plein écran quitté',
  fullscreen_enter: 'Plein écran activé',
  screen_share_stopped: "Partage d'écran arrêté",
  copy_attempt: 'Tentative de copie',
  paste_attempt: 'Tentative de collage',
  right_click: 'Clic droit',
  devtools_attempt: "Tentative d'ouverture des outils développeur",
  multiple_faces: 'Plusieurs visages détectés',
  camera_blocked: 'Caméra obstruée',
  session_end: 'Fin de session',
  warning_issued: 'Avertissement émis',
  proctor_note: 'Note du surveillant',
  proctor_ban: 'Exclusion par le surveillant',
  extra_time: 'Temps supplémentaire accordé',
  unban: 'Débannissement',
  student_call_request: "Demande d'appel de l'étudiant",
  call_request: "Demande d'appel",
  student_message: 'Message étudiant',
  student_resumed: 'Reprise après déconnexion',
  student_break: 'Pause demandée par l\'étudiant',
  student_banned: 'Étudiant exclu',
  network_reconnected: 'Réseau rétabli',
  network_disconnected: 'Réseau coupé',
  network_quality: 'Qualité du réseau',
  camera_quality: 'Qualité de la caméra',
}

export function eventLabel(type: string | null | undefined, local?: Record<string, string>): string {
  if (!type) return 'Événement de surveillance'
  const t = String(type)
  return local?.[t] ?? local?.[t.toLowerCase()] ?? SHARED[t] ?? SHARED[t.toLowerCase()] ?? 'Événement de surveillance'
}
